// ============================================================================
// Peripheral Agentic OS — Four-Layer Attribution System
// ============================================================================

import crypto from 'crypto';
import { eventBus } from '../core/event-bus.js';
import type { AttributionRecord, VisibleCredit, HMACSignature, SteganographicWatermark } from '../types/attribution.js';

/** Zero-width characters for steganographic watermarking */
const ZW_CHARS = ['\u200B', '\u200C', '\u200D', '\uFEFF']; // ZWSP, ZWNJ, ZWJ, BOM

/**
 * Content Signer: Visible credits + HMAC-SHA256 signing.
 */
export class ContentSigner {
  private hmacKey: Buffer;

  constructor(keyHex?: string) {
    this.hmacKey = keyHex ? Buffer.from(keyHex, 'hex') : crypto.randomBytes(32);
  }

  /** Add visible credit line */
  addVisibleCredit(content: string, model: string, provider: string, taskId: string): { content: string; credit: VisibleCredit } {
    const credit: VisibleCredit = {
      text: `[Generated by Peripheral Agentic OS | Model: ${model} | Provider: ${provider} | ${new Date().toISOString()}]`,
      model, provider, timestamp: new Date().toISOString(), taskId,
    };
    return { content: `${content}\n\n---\n${credit.text}`, credit };
  }

  /** Sign content with HMAC-SHA256 */
  sign(content: string, taskId: string): HMACSignature {
    const contentHash = crypto.createHash('sha256').update(content).digest('hex');
    const hmac = crypto.createHmac('sha256', this.hmacKey);
    hmac.update(content);
    const signature = hmac.digest('hex');

    eventBus.emit('attribution:signed', { taskId, contentHash: contentHash.substring(0, 16) }, 'ContentSigner');

    return {
      algorithm: 'sha256', signature, keyId: crypto.createHash('sha256').update(this.hmacKey).digest('hex').substring(0, 16),
      contentHash, timestamp: new Date().toISOString(),
    };
  }

  /** Verify an HMAC signature */
  verify(content: string, signature: string): boolean {
    const hmac = crypto.createHmac('sha256', this.hmacKey);
    hmac.update(content);
    const expected = hmac.digest('hex');
    const valid = crypto.timingSafeEqual(Buffer.from(signature, 'hex'), Buffer.from(expected, 'hex'));
    if (!valid) {
      eventBus.emit('attribution:tamper_detected', {}, 'ContentSigner');
    }
    return valid;
  }
}

/**
 * Steganographic Watermark: Embeds metadata using zero-width Unicode characters.
 */
export class SteganographicWatermarker {
  /** Encode metadata into text using zero-width characters */
  embed(text: string, metadata: Record<string, string>): { text: string; watermark: SteganographicWatermark } {
    const payload = Buffer.from(JSON.stringify(metadata)).toString('base64');
    const encoded = this.encodeBits(payload);

    // Insert watermark characters after the first sentence
    const insertPoint = text.indexOf('.') + 1;
    const watermarkedText = insertPoint > 0
      ? text.substring(0, insertPoint) + encoded + text.substring(insertPoint)
      : encoded + text;

    const watermark: SteganographicWatermark = {
      encoded: true, payload, method: 'zero_width', markerCount: encoded.length,
    };

    eventBus.emit('attribution:watermarked', { payloadSize: payload.length }, 'Watermarker');
    return { text: watermarkedText, watermark };
  }

  /** Extract watermark from text */
  extract(text: string): Record<string, string> | null {
    const zwRegex = /[\u200B\u200C\u200D\uFEFF]+/;
    const match = text.match(zwRegex);
    if (!match) return null;

    try {
      const payload = this.decodeBits(match[0]);
      return JSON.parse(Buffer.from(payload, 'base64').toString('utf8'));
    } catch {
      return null;
    }
  }

  /** Remove watermark from text */
  strip(text: string): string {
    return text.replace(/[\u200B\u200C\u200D\uFEFF]/g, '');
  }

  private encodeBits(str: string): string {
    let result = '';
    for (const char of str) {
      const code = char.charCodeAt(0);
      for (let bit = 7; bit >= 0; bit--) {
        const value = (code >> bit) & 0x03; // 2-bit groups
        result += ZW_CHARS[value];
      }
    }
    return result;
  }

  private decodeBits(encoded: string): string {
    let result = '';
    for (let i = 0; i < encoded.length; i += 4) {
      let code = 0;
      for (let j = 0; j < 4 && i + j < encoded.length; j++) {
        const value = ZW_CHARS.indexOf(encoded[i + j]);
        if (value >= 0) code = (code << 2) | value;
      }
      if (code > 0) result += String.fromCharCode(code);
    }
    return result;
  }
}

/**
 * Full Attribution Pipeline combining all 4 layers.
 */
export class AttributionPipeline {
  private signer: ContentSigner;
  private watermarker: SteganographicWatermarker;

  constructor(hmacKeyHex?: string) {
    this.signer = new ContentSigner(hmacKeyHex);
    this.watermarker = new SteganographicWatermarker();
  }

  /** Apply full attribution to content */
  apply(content: string, taskId: string, model: string, provider: string): {
    content: string;
    record: AttributionRecord;
  } {
    // Layer 1: Visible credit
    const { content: creditedContent, credit } = this.signer.addVisibleCredit(content, model, provider, taskId);

    // Layer 2: HMAC signing
    const hmac = this.signer.sign(content, taskId);

    // Layer 3: Steganographic watermark
    const { text: watermarkedContent, watermark } = this.watermarker.embed(creditedContent, {
      taskId, model, provider, timestamp: new Date().toISOString(),
    });

    // Layer 4: Blockchain timestamp (placeholder — would call OpenTimestamps)
    const record: AttributionRecord = {
      id: crypto.randomUUID(),
      taskId,
      contentHash: hmac.contentHash,
      layers: {
        visible: credit,
        hmac,
        steganographic: watermark,
        blockchain: { hash: hmac.contentHash, protocol: 'opentimestamps', anchor: 'bitcoin', status: 'pending' },
      },
      createdAt: new Date().toISOString(),
    };

    return { content: watermarkedContent, record };
  }

  getSigner(): ContentSigner { return this.signer; }
  getWatermarker(): SteganographicWatermarker { return this.watermarker; }
}
